version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - pip install .[docs]
    - pip install -r docs/requirements.txt
    - cd docs/ && make html
    - mkdir _readthedocs/
    - mv docs/build/html/ _readthedocs/
