name: main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  REPO_NAME: ${{ github.event.repository.name }}
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v2
      - name: python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install
        run: pip install .[testing]
      - name: pytest
        run: python -m pytest --verbose --cov=./${REPO_NAME}/ --cov-report xml
      - name: codecov
        uses: codecov/codecov-action@v3
        with:
          name: codecov-umbrella
          verbose: true
      - name: pylint
        run: |
          python -m pylint --disable=C0103 --output-format=text statmechcrack | tee lint.log || pylint-exit $?