name: pages
on:
  push:
    branches: [ main ]
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: pip install .[all]
      - name: docs
        run: |
          cd docs/ && make html
          mv build/html/ ../public/
      - name: Deploy docs to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/