name: pages
on:
  push:
    branches: [ main ]
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install package and docs extras
        run: pip install .[all]
      - name: pylint badge
        run: |
          python -m pylint --disable=C0103 --output-format=text statmechcrack | tee pylint.log || pylint-exit $?
          PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.log)
          if (( $(echo "${PYLINT_SCORE} >= 8.0" | bc -l) )); then
            COLOR=brightgreen
          elif (( $(echo "${PYLINT_SCORE} >= 4.0" | bc -l) )); then
            COLOR=yellow
          elif (( $(echo "${PYLINT_SCORE} >= 2.0" | bc -l) )); then
            COLOR=orange
          else
            COLOR=red
          fi
          curl "https://img.shields.io/badge/Pylint-${PYLINT_SCORE}-${COLOR}?logo=python&logoColor=FBE072" -o pylint.svg
      - name: Build docs
        run: |
          sudo apt-get install pandoc
          source .github/workflows/docs.sh
          sphinx-build -b html source/ build/html/
          sed -i -e "s/ module</</g" build/html/*.html
          sed -i '/Built with/,/Docs<\/a>./d' build/html/*.html
          mv build/html/ ../public/
          mv ../pylint.svg ../public/
      - name: Deploy docs to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public/